### ISSUE TITLE
Should ping assignee

### ISSUE THREAD

**Issue by michael-hawker** [nmetulev/github-bot-uwp-toolkit#17]
Noticed on [this issue](https://github.com/windows-toolkit/WindowsCommunityToolkit/pull/2617) bot pinged initial author instead of assignee.

Does it also handle knowing if it should ping the author/assignee vs. those who've left comments for review to address?

**Comment by nmetulev** [comment]
It currently only pings the author for PRs. We did not take into account that a PR might be opened by one person but assigned to another. It should probably ping both if PR is assigned.

**Comment by Odonno** [comment]
If any, I can surely use the list of assignees to ping in a PR. https://developer.github.com/v4/object/pullrequest/#assignees

**Comment by Odonno** [comment]
Should it work for both PRs and issues?
